# Generated by Django 4.2.19 on 2025-04-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('made_in', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
